CREATE DATABASE IF NOT EXISTS E2;

USE E2;

CREATE TABLE IF NOT EXISTS INSTRUMENTOS(
    ID INT NOT NULL AUTO_INCREMENT,
    MARCA VARCHAR(255) NOT NULL,
    MODELO VARCHAR(255) NOT NULL,
    COR VARCHAR(255) NOT NULL,
    CORDAS INT NOT NULL,
    PRIMARY KEY(ID)
);